const BOOK_AUDIO_MAP = {
  genesis: { number: '01', name: 'Genesis' },
  exodus: { number: '02', name: 'Exodus' },
  leviticus: { number: '03', name: 'Leviticus' },
  numbers: { number: '04', name: 'Numbers' },
  deuteronomy: { number: '05', name: 'Deuteronomy' },
  joshua: { number: '06', name: 'Joshua' },
  judges: { number: '07', name: 'Judges' },
  ruth: { number: '08', name: 'Ruth' },
  '1-samuel': { number: '09', name: 'First_Samuel' },
  '2-samuel': { number: '10', name: 'Second_Samuel' },
  '1-kings': { number: '11', name: 'First_Kings' },
  '2-kings': { number: '12', name: 'Second_Kings' },
  '1-chronicles': { number: '13', name: 'First_Chronicles' },
  '2-chronicles': { number: '14', name: 'Second_Chronicles' },
  ezra: { number: '15', name: 'Ezra' },
  nehemiah: { number: '16', name: 'Nehemiah' },
  esther: { number: '17', name: 'Esther' },
  job: { number: '18', name: 'Job' },
  psalms: { number: '19', name: 'Psalms' },
  proverbs: { number: '20', name: 'Proverbs' },
  ecclesiastes: { number: '21', name: 'Ecclesiastes' },
  'song-of-solomon': { number: '22', name: 'Song_of_Solomon' },
  isaiah: { number: '23', name: 'Isaiah' },
  jeremiah: { number: '24', name: 'Jeremiah' },
  lamentations: { number: '25', name: 'Lamentations' },
  ezekiel: { number: '26', name: 'Ezekiel' },
  daniel: { number: '27', name: 'Daniel' },
  hosea: { number: '28', name: 'Hosea' },
  joel: { number: '29', name: 'Joel' },
  amos: { number: '30', name: 'Amos' },
  obadiah: { number: '31', name: 'Obadiah' },
  jonah: { number: '32', name: 'Jonah' },
  micah: { number: '33', name: 'Micah' },
  nahum: { number: '34', name: 'Nahum' },
  habakkuk: { number: '35', name: 'Habakkuk' },
  zephaniah: { number: '36', name: 'Zephaniah' },
  haggai: { number: '37', name: 'Haggai' },
  zechariah: { number: '38', name: 'Zechariah' },
  malachi: { number: '39', name: 'Malachi' },
  matthew: { number: '40', name: 'Matthew' },
  mark: { number: '41', name: 'Mark' },
  luke: { number: '42', name: 'Luke' },
  john: { number: '43', name: 'John' },
  acts: { number: '44', name: 'Acts' },
  romans: { number: '45', name: 'Romans' },
  '1-corinthians': { number: '46', name: 'First_Corinthians' },
  '2-corinthians': { number: '47', name: 'Second_Corinthians' },
  galatians: { number: '48', name: 'Galatians' },
  ephesians: { number: '49', name: 'Ephesians' },
  philippians: { number: '50', name: 'Philippians' },
  colossians: { number: '51', name: 'Colossians' },
  '1-thessalonians': { number: '52', name: 'First_Thessalonians' },
  '2-thessalonians': { number: '53', name: 'Second_Thessalonians' },
  '1-timothy': { number: '54', name: 'First_Timothy' },
  '2-timothy': { number: '55', name: 'Second_Timothy' },
  titus: { number: '56', name: 'Titus' },
  philemon: { number: '57', name: 'Philemon' },
  hebrews: { number: '58', name: 'Hebrews' },
  james: { number: '59', name: 'James' },
  '1-peter': { number: '60', name: 'First_Peter' },
  '2-peter': { number: '61', name: 'Second_Peter' },
  '1-john': { number: '62', name: 'First_John' },
  '2-john': { number: '63', name: 'Second_John' },
  '3-john': { number: '64', name: 'Third_John' },
  jude: { number: '65', name: 'Jude' },
  revelation: { number: '66', name: 'Revelation' },
}

const CHAPTER_WORDS = {
  1: 'One',
  2: 'Two',
  3: 'Three',
  4: 'Four',
  5: 'Five',
  6: 'Six',
  7: 'Seven',
  8: 'Eight',
  9: 'Nine',
  10: 'Ten',
  11: 'Eleven',
  12: 'Twelve',
  13: 'Thirteen',
  14: 'Fourteen',
  15: 'Fifteen',
  16: 'Sixteen',
  17: 'Seventeen',
  18: 'Eighteen',
  19: 'Nineteen',
  20: 'Twenty',
  21: 'Twenty_One',
  22: 'Twenty_Two',
  23: 'Twenty_Three',
  24: 'Twenty_Four',
  25: 'Twenty_Five',
  26: 'Twenty_Six',
  27: 'Twenty_Seven',
  28: 'Twenty_Eight',
  29: 'Twenty_Nine',
  30: 'Thirty',
  31: 'Thirty_One',
  32: 'Thirty_Two',
  33: 'Thirty_Three',
  34: 'Thirty_Four',
  35: 'Thirty_Five',
  36: 'Thirty_Six',
  37: 'Thirty_Seven',
  38: 'Thirty_Eight',
  39: 'Thirty_Nine',
  40: 'Forty',
  41: 'Forty_One',
  42: 'Forty_Two',
  43: 'Forty_Three',
  44: 'Forty_Four',
  45: 'Forty_Five',
  46: 'Forty_Six',
  47: 'Forty_Seven',
  48: 'Forty_Eight',
  49: 'Forty_Nine',
  50: 'Fifty',
  51: 'Fifty_One',
  52: 'Fifty_Two',
  53: 'Fifty_Three',
  54: 'Fifty_Four',
  55: 'Fifty_Five',
  56: 'Fifty_Six',
  57: 'Fifty_Seven',
  58: 'Fifty_Eight',
  59: 'Fifty_Nine',
  60: 'Sixty',
  61: 'Sixty_One',
  62: 'Sixty_Two',
  63: 'Sixty_Three',
  64: 'Sixty_Four',
  65: 'Sixty_Five',
  66: 'Sixty_Six',
  67: 'Sixty_Seven',
  68: 'Sixty_Eight',
  69: 'Sixty_Nine',
  70: 'Seventy',
  71: 'Seventy_One',
  72: 'Seventy_Two',
  73: 'Seventy_Three',
  74: 'Seventy_Four',
  75: 'Seventy_Five',
  76: 'Seventy_Six',
  77: 'Seventy_Seven',
  78: 'Seventy_Eight',
  79: 'Seventy_Nine',
  80: 'Eighty',
  81: 'Eighty_One',
  82: 'Eighty_Two',
  83: 'Eighty_Three',
  84: 'Eighty_Four',
  85: 'Eighty_Five',
  86: 'Eighty_Six',
  87: 'Eighty_Seven',
  88: 'Eighty_Eight',
  89: 'Eighty_Nine',
  90: 'Ninety',
  91: 'Ninety_One',
  92: 'Ninety_Two',
  93: 'Ninety_Three',
  94: 'Ninety_Four',
  95: 'Ninety_Five',
  96: 'Ninety_Six',
  97: 'Ninety_Seven',
  98: 'Ninety_Eight',
  99: 'Ninety_Nine',
  100: 'One_Hundred',
  101: 'One_Hundred_One',
  102: 'One_Hundred_Two',
  103: 'One_Hundred_Three',
  104: 'One_Hundred_Four',
  105: 'One_Hundred_Five',
  106: 'One_Hundred_Six',
  107: 'One_Hundred_Seven',
  108: 'One_Hundred_Eight',
  109: 'One_Hundred_Nine',
  110: 'One_Hundred_Ten',
  111: 'One_Hundred_Eleven',
  112: 'One_Hundred_Twelve',
  113: 'One_Hundred_Thirteen',
  114: 'One_Hundred_Fourteen',
  115: 'One_Hundred_Fifteen',
  116: 'One_Hundred_Sixteen',
  117: 'One_Hundred_Seventeen',
  118: 'One_Hundred_Eighteen',
  119: 'One_Hundred_Nineteen',
  120: 'One_Hundred_Twenty',
  121: 'One_Hundred_Twenty_One',
  122: 'One_Hundred_Twenty_Two',
  123: 'One_Hundred_Twenty_Three',
  124: 'One_Hundred_Twenty_Four',
  125: 'One_Hundred_Twenty_Five',
  126: 'One_Hundred_Twenty_Six',
  127: 'One_Hundred_Twenty_Seven',
  128: 'One_Hundred_Twenty_Eight',
  129: 'One_Hundred_Twenty_Nine',
  130: 'One_Hundred_Thirty',
  131: 'One_Hundred_Thirty_One',
  132: 'One_Hundred_Thirty_Two',
  133: 'One_Hundred_Thirty_Three',
  134: 'One_Hundred_Thirty_Four',
  135: 'One_Hundred_Thirty_Five',
  136: 'One_Hundred_Thirty_Six',
  137: 'One_Hundred_Thirty_Seven',
  138: 'One_Hundred_Thirty_Eight',
  139: 'One_Hundred_Thirty_Nine',
  140: 'One_Hundred_Forty',
  141: 'One_Hundred_Forty_One',
  142: 'One_Hundred_Forty_Two',
  143: 'One_Hundred_Forty_Three',
  144: 'One_Hundred_Forty_Four',
  145: 'One_Hundred_Forty_Five',
  146: 'One_Hundred_Forty_Six',
  147: 'One_Hundred_Forty_Seven',
  148: 'One_Hundred_Forty_Eight',
  149: 'One_Hundred_Forty_Nine',
  150: 'One_Hundred_Fifty',
}

export function getBibleAudioUrl(bookSlug, chapter) {
  const bookAudio = BOOK_AUDIO_MAP[bookSlug]
  const chapterNumber = Number(chapter)
  const chapterWord = CHAPTER_WORDS[chapterNumber]

  if (!bookAudio || !chapterWord) return null

  const paddedChapter = String(chapterNumber).padStart(2, '0')

  return `/audio/web/${bookAudio.number}_${bookAudio.name}/${bookAudio.number}_${paddedChapter}_${bookAudio.name}_Chapter_${chapterWord}.mp3`
}